### ISSUE TITLE
Organize Data set

### ISSUE THREAD

**Issue by Kgable** [Kgable/Soc-413-Research-Project#10]
Good morning @AaronGullickson 
  My apologies for not sending this Monday. I thought I had. I didn't push my work or send the message. Again, my apologies.  I have my code in the organize data folder. I still have a couple of questions. 
1) When I looked at the racial categories I tries to build the categories. I am not sure how to include a multiracial category using the second question, there will seem to be a small group left over classified as other. Should I drop them? 
2) I renamed the religious importance variable, but reordering it seems odd in an ifelse statement. (I am concerned about mislabeling data.) Can I put that nested statement within the section I am already renaming the variable? Here is my thought, 
gss$reliten <- factor(ifelse(gss$reliten==1, "2"). Would this reordering do anything to the outcome of the data? Or, does it not make a difference what number value I reorder it in?

Thank you for your support,
Kevin Gable

**Comment by AaronGullickson** [comment]
Hi @Kgable. On question 1, here is the distribution of `racecen2`:

```r
table(gss$racecen2, exclude=NULL)

    1     2     3     4     5     6     7     8     9    10    11    12    13    14    15    16  <NA> 
  359   166  1045    21    43    35    31    15     7    32    17     7     8    13    56   172 70363 
```

Those 70,363 NAs are cases where someone did not report a second race. So, the simple solution is to check `is.na(gss$racecen2)` and if this is ~true~false, the person goes in to the multiracial category and if not, then you proceed to classify them based on `racecen1`. I would put this as your first `ifelse` check - or better yet, just do a `case_when`.

Also looking through that code, I saw this:

```r
ifelse(gss$hispanic>=2 & gss$hispanic<=47,  "hispanic", ...
```

That code is saying all categories between 2 and 47 go to hispanic, which can't be right because you are then trying to code Asian and indigenous in later lines.

On the second question, we need to do some thinking about the `reliten` variable. Here is its distribution.

```r
table(gss$reliten, exclude=NULL)

    1     2     3     4  <NA> 
22652 23738  5736  7629 12635 
```

A lot of cases are missing there - this is not just item non-response. Some people are not asked this question. It could be because it was not available on all ballots in all years or it could be that some people were not asked based on answer to previous question (perhaps that they had no religious affiliation?).  So lets get to the bottom of that issue first.

Assuming we get it sorted, there are a couple of ways you could re-order but simplest and most readable would probably be a case_when:

```r
gss <- gss |>
  mutate(relig_imp=case_when(
    reliten==1 ~ 4, # strong
    reliten==2 ~ 2, # not strong
    reliten==3 ~ 3, # somewhat strong
    reliten==4 ~ 1, # no religion
  ))

table(gss$reliten, gss$relig_imp, exclude=NULL)

      
           1     2     3     4  <NA>
  1        0     0     0 22652     0
  2        0 23738     0     0     0
  3        0     0  5736     0     0
  4     7629     0     0     0     0
  <NA>     0     0     0     0 12635
```

**Comment by Kgable** [comment]
Dear Dr Gullickson,

   Good morning, I hope all is well. Thank you so much for your support. I was looking at information on the reliten variable and it turns out, this question was asked of those who gave an answer to the religious preference question indicating an association with a listed religion. There were also some weighting issues from data in the 1980's. This shouldn't impact much because the interest begins in 2000. However, there was an additional consideration beginning in 2004 and it is listed as such.
4 Beginning in 2004, the GSS began to use a two-stage sub-sampling design for nonresponse. To obtain weighted estimates adjusted for this non-response, users should use the WTSSNR weight in these years.
 I will begin to work on the race variable. When I was trying to code the Hispanic variable, I thought I was grabbing it from the Hispanic question than racecen1. I will work on it and fix it.
Are we meeting today? I believe you are out of town, and I don't want to interfere. I will be available. However, you have given me some good stuff to work on and if you need to reschedule that is okay. I couldn't remember what we agreed on for today's check in last week. Again, thank you for your support.

Thank you,
Kevin Gable
________________________________
