### ISSUE TITLE
Cleaning Data

### ISSUE THREAD

**Issue by Kgable** [Kgable/Soc-413-Research-Project#4]
Good afternoon @AaronGullickson, 
     I hope all is well. I am getting close to finishing my analytical data set. I have coded the missing values, collapsed necessary variables to categories, and renamed the input of the variables, before sex = 1, now = male for example. What I still need to do is standardize the four remaining religiosity variables. In math terms, this looks like, x = x-xmax / xmax-xmin. For the life of me I can't think of how this looks in Rcode. How do I standardize my religiosity variables?
     I have office hours scheduled for tomorrow at 4. I also committed and pushed the work I have done so far. You can see the variables I have created. I have not ran the final save section yet, but the variables identified in that "save it all" section are the variables of interest. 
Thank you,
Kevin Gable

**Comment by AaronGullickson** [comment]
You could rescale like that, although I would use xmin rather than xmax in the numerator, so that 0 is your lowest possible value and 1 is your highest possible value. You should just be able to use the `min` and `max` functions in R:

```r
x_rescale <- (x-min(x))/(max(x)-min(x))
```

An alternative scaling would be to "standardize" by subtracting the mean and dividing by the standard deviation which you can do with the `scale` command. Its a different kind of scaling. The first kind of scaling above will give you a 0-1 range for each variable but they still may have very different means depending on the distribution of the variable. For example, mean belief in god will be much higher on this scale than mean religious attendance. This is basically what I do in my Soc Sci article in Figure 2. If you instead standardize, then you bring the entire distributions into line with each other (they all have mean 0 and SD 1). I think the first approach can be good if you want to keep the variables separate for the analysis but want to give them a similar unit scale for comparison, while the second is good if you want to combine variables to create a synthetic religiosity measure.

**Comment by Kgable** [comment]
Good morning Professor Gullickson,

   I hope all is well. I decided to use factor analysis to create my religiosity variable and I dropped the belief in afterlife due to the low count of data. I used the standardization function. I assume it is still working and I am experiencing user error. I used the summary command and I still don't see a mean of 0. I think I am using the wrong command to check that. How do I list the mean and sd?
   However, I successfully added the psych package in the utilities section and the script worked great in the organize data file! I just need to verify my mean of 0 and sd of 1, then check my factor variables loadings and I may be ready to save it all to my final data folder.
  I chose to convert the three remaining religiosity composite variables into qualitative variables under new variable names as well as standardize the originals so I can potentially explore them as a collective and individually across cohorts.
Thank you,
Kevin Gable

**Comment by Kgable** [comment]
Dear Dr Gullickson,
  I forgot to mention. I have committed and pushed the coding I have done. This includes both the standardization and factor analysis. 

Thank you,
Kevin Gable

**Comment by Kgable** [comment]
Dear Dr Gullickson,
  I apologize for the emails. I got it!. However, I have noticed my sd in the case of religious attendance varies between -1.3 and 1.5. Is that normal?

Thank you,
Kevin Gable

**Comment by Kgable** [comment]
Good morning @AaronGullickson 

    Hello, I was sending some messages yesterday and realized I didn't format them to alert you. I apologize for taking up your time. I am really close with building my analytical dataset. Please feel free to ignore the previous messages as the info is here too.
    I decided to use factor analysis to create my religiosity variable and I dropped the belief in afterlife due to the low count of data. I used the standardization function and I noticed something strange. I get means of zero when I use the summary command. However, my standard deviations are not equal to one. In some cases, they are not close to one either. Any idea how to fix that? I haven't combined them into religiosity yet and tested that code. I wanted to make sure they were standardized correctly first. 
     Also, I successfully added the psych package in the utilities section and the script worked great in the organize data file!
I chose to convert the three remaining religiosity composite variables into qualitative variables under new variable names as well as standardize the originals so I can potentially explore them collectively and individually across cohorts. I thought it might be nice to leave options. 

Thank you,
Kevin Gable
