### ISSUE TITLE
Final Paper

### ISSUE THREAD

**Issue by Kgable** [Kgable/Soc-413-Research-Project#9]
Good morning @AaronGullickson,
  I am set to turn in my final paper. When I rendered the document I noticed two things. First, it didn't recognize my separate paragraphs in the methods section. So, it's one long paragraph for some reason. This doesn't happen in other sections. Two, when I refer to my graphs with the @-fig command it doesn't seem to work like I thought it would. It doesn't say figure 1 or 2, it prints the command. I also have some funny looks to the boarders of my table of models. Do these issues matter overall for this assignment, should I just turn it in as is? I committed and pushed my final work to git. 
Thank you,
Kevin Gable

**Comment by AaronGullickson** [comment]
Regarding the massive paragraphs - you must leave an empty line between paragraphs for markdown to recognize paragraph breaks.

Regarding the @-fig command - I think most of them work, but the first one on line 57 you have Label rather than label. It works when I fix that.

On the table of models, remember to put `#| results: asis` in the code chunk options at the top.

**Comment by Kgable** [comment]
Thank you @AaronGullickson 
  I think it is ready. When I tried to reference the table of models in the text (@fig-Rendering_Models) it doesn't work with that command. All the graphs are working great. Is this because it is a table and not a graph? I am also sure my model explanations need work, but that seems to be my struggle on each assignment. I would be thrilled fixing the table rendering reference. Either way, I will have it in by 5.

Thank you,
Kevin Gable

**Comment by AaronGullickson** [comment]
texreg is not fully quarto aware yet. Should be soon! Just refer to the table the old fashioned way in the text.
